name: Makefile CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Verify environment variables
      - name: Verify .env file
        run: make env-check

      # Lint and format checks
      - name: Lint code
        run: make lint
      - name: Check formatting
        run: make check-format

      # Run Cypress tests
      - name: Run tests
        run: make test-headless

      # Build application
      - name: Build application
        run: make build

  docker-build-and-push:
    runs-on: ubuntu-latest

    needs: build-and-test

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: make docker-build

      # Push Docker image to DockerHub
      - name: Push Docker image
        run: |
          docker tag $(APP_NAME):latest ${DOCKER_USERNAME}/$(APP_NAME):latest
          docker push ${DOCKER_USERNAME}/$(APP_NAME):latest
